#' @title qplot_driver
#' @description Generates a driver graph showing the positive and negative effects
#' from a key driver model in a tornado-type graph.  Output for Key Driver Analyses.
#' @param data Dataframe or tibble containing the output from a modeling process.
#' Expects two columns minimum: term, estimate.  Examine \code{qplot::coefs1} for
#' an example file that is generated by \code{qmod::get_driver_coefs}.
#' @param labels Dataframe that contains the label names to be used in the graphic
#' output on the plot rather than the default variable names that may be found in
#' the dataset.  Expects 2 columns named var and label.  Examine \code{qplot::labels1}
#' as an example dataframe for this parameter.  Optional.
#' @param output Character string containing the complete path and file name of
#' a png file of the resulting performance plot.  If not provided, the plot will
#' be shown on the screen instead but may not be optimized for screen viewing.
#' Optional.
#' @param sort Logical indicating of the data should be sorted in descending order
#' of magnitude (taking into account both positive and negative impact combined).
#' Default: TRUE
#' @param legend A logical value indicating if a legend containing the Labels of
#' Positive, Neutral, and Negative along with their corresponding colors should
#' be displayed in the bottom right-hand corner of the plot. Default: TRUE
#' @param decimals Numeric value indicating the number of decimals to use for
#' rounding the displayed numbers in the graph. Default: 1
#' @param skeleton A logical value to indicate if the syntax should be printed to
#' the console.  This is useful if the default selections need tweaking so the
#' user can see the raw syntax that can be used in place of the function.
#' Default: FALSE
#' @param ps Point size setting for grDevices::jpeg.  May need to reduce if lots
#' of attributes are included.  Default=12.
#' @return Outputs a png file of the driver plot if output path specified,
#' otherwise generates plot on screen.
#' @examples
#' \dontrun{
#' if(interactive()){
#'  qplot_driver(data=qplot::coefs1, labels=qplot::labels1)
#'  }
#' }
#' @export
#' @importFrom fs path_ext
#' @importFrom ggplot2 ggplot geom_bar geom_text coord_flip scale_x_discrete ylim geom_hline labs theme_minimal scale_fill_manual theme

qplot_driver <- function(data=NULL, labels=NULL, output=NULL,
                         sort=TRUE, legend=TRUE, decimals=1, skeleton=FALSE, ps=12){

  # Checks ------------------------------------------------------------------

  if (is.null(data)){
    stop(call. = FALSE, "Data must be specified.")
  }

  if (is.null(labels)){
    warning("No label file is specified; using variable names instead")
  }

  # Filenames ---------------------------------------------------------------

  if (is.null(output) == FALSE){
    if(fs::path_ext(output) %in% c("png")){
      plot_path <- output
    } else {
      plot_path <- paste0(output, ".png")
    }
  }

  # Prep Data ---------------------------------------------------------------

  plot_data <- process_coefs(DATA=data, LABELS=labels, DECIMALS=decimals, SORT=sort)

    # Key Driver Plot ---------------------------------------------------------

  if(skeleton==TRUE){

    cat(paste0("plot_data <- qplot::process_coefs(DATA=data, LABELS=labels, DECIMALS=decimals, SORT=sort)

               driver_plot <- plot_data$data %>%
  ggplot2::ggplot(aes(x = label, y = estimate, group = hilo, fill = hilo)) +
  ggplot2::geom_bar(stat = \"identity\", width=.8) +
  ggplot2::geom_text(aes(label=bar_label, hjust=bar_just, fontface=\"bold\"), size=3) +
  ggplot2::coord_flip() +
  ggplot2::scale_x_discrete(limits = names(plot_data$order)) +
  ggplot2::ylim(min(as.numeric(plot_data$data$label_low), na.rm=TRUE)-10,
                max(as.numeric(plot_data$data$label_high), na.rm=TRUE)+10) +
  ggplot2::geom_hline(yintercept=0, color=\"black\", linewidth=.15) +
  ggplot2::labs(title=NULL, y=NULL, x=NULL) +
  ggplot2::theme_minimal() +
  ggplot2::scale_fill_manual(values=c(\"Perform Poorly\"=\"#FF0000\", \"Perform Well\" = \"#008000\")) +
  ggplot2::theme(legend.title = element_blank(),
                 legend.text = element_text(size=8),
                 legend.key.size = unit(4, \"mm\"),
                 plot.title = element_blank(),
                 panel.background = element_blank(),
                 panel.grid = element_blank(),
                 axis.text.x=element_blank(),
                 plot.margin = margin(1,1,1,1, \"mm\"))+
  ggplot2::theme(legend.position = c(.9, .05)) +
  ggplot2::theme(axis.text.y=element_text(size=10, face=\"bold\", color=\"black\"))

png(OUTPUT_FILE_PATH_HERE, width=1920, height=1080, res=300, pointsize=12)
print(driver_plot)
invisible(dev.off())"))

  } else {

    driver_plot <- plot_data$data %>%
      ggplot2::ggplot(aes(x = label, y = estimate, group = hilo, fill = hilo)) +
      ggplot2::geom_bar(stat = "identity", width=.8) +
      ggplot2::geom_text(aes(label=bar_label, hjust=bar_just, fontface="bold"), size=3) +
      ggplot2::coord_flip() +
      ggplot2::scale_x_discrete(limits = names(plot_data$order)) +
      ggplot2::ylim(min(as.numeric(plot_data$data$label_low), na.rm=TRUE)-10,
                    max(as.numeric(plot_data$data$label_high), na.rm=TRUE)+10) +
      ggplot2::geom_hline(yintercept=0, color="black", linewidth=.15) +
      ggplot2::labs(title=NULL, y=NULL, x=NULL) +
      ggplot2::theme_minimal() +
      ggplot2::scale_fill_manual(values=c("Perform Poorly"="#FF0000", "Perform Well" = "#008000")) +
      ggplot2::theme(legend.title = element_blank(),
                     legend.text = element_text(size=8),
                     legend.key.size = unit(4, "mm"),
                     plot.title = element_blank(),
                     panel.background = element_blank(),
                     panel.grid = element_blank(),
                     axis.text.x=element_blank(),
                     plot.margin = margin(1,1,1,1, "mm"))

    #Display on screen
    if (is.null(output)){

      if (legend == FALSE){
        driver_plot <- driver_plot +
          ggplot2::theme(legend.position = "none")
      } else {
        driver_plot <- driver_plot +
          ggplot2::theme(legend.position = c(.92, .05))
      }

      driver_plot <- driver_plot +
        ggplot2::theme(axis.text.y=element_text(size=12, face="bold", color="black"))

      print(driver_plot)

      #Saved as png
    } else {

      if (legend == FALSE){
        driver_plot <- driver_plot +
          ggplot2::theme(legend.position = "none")
      } else {
        driver_plot <- driver_plot +
          ggplot2::theme(legend.position = c(.9, .05))
      }

      driver_plot <- driver_plot +
        ggplot2::theme(axis.text.y=element_text(size=10, face="bold", color="black"))
      png(plot_path, width=1920, height=1080, res=300, pointsize=ps)
      print(driver_plot)
      invisible(dev.off())
    }

  }



}
